### ISSUE TITLE
Error running tests

### ISSUE THREAD

**Issue by bitstormFA** [haxscramper/hcparse#4]
Hi,

First let me say that this could be the killer app for nim! Many thanks for your effort.

I have started some tests to use it but get errors that "skip1" is undeclared.
To check if this was based on my code I tried the to run nimble test and got the same error:
`Error: attempting to call undeclared routine: 'skip1'`

My configuration is 
OS: Arch Linux
Nim 1.4.8 

I did run the test on commit  541110d2f1365b9935c5acf626c39c466d23de7f 
My experience with nim is very limited so please excuse if the mistake is on my side.

**Comment by haxscramper** [comment]
I did a large refactoring in one of the dependencies, which is most likely to be the cause of the error. Thanks for reporting, I will keep this in mind.

**Comment by haxscramper** [comment]
Finally set up the CI, so at least some level of test reproducibility exists, although right now the project is still in very early stage and there are not a lot of things that can be used reliably anyway.
